# -*- coding: utf-8 -*-
"""linearrreg (data).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16woMDzHbQs1L48qZen5ZJCZCZFIGHB8l
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/data.csv')

df.head()

df.columns

df.shape

df.info()

df.drop('Name', axis=1, inplace=True)

df['Department'].value_counts()

sns.countplot(x='Department', data=df)
plt.show()

df['Gender'].value_counts()

sns.countplot(x='Gender',data=df);
plt.show()

df['Salary'].value_counts()

sns.countplot(x='Salary',data=df)
plt.show()

df['City'].value_counts()

sns.countplot(x='City',data=df)
plt.show()

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
pd.crosstab(df.Department,df.Job_Title).plot(kind='bar')
plt.title('employee department')
plt.xlabel('Department')
plt.ylabel('Number of Jobs')

X=df[['Age', 'Department','Gender','Job_Title', 'Salary', 'City',
       'Phone',  'Active_Status']]
y=df['Active_Status']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()

# Identify categorical columns that need one-hot encoding
categorical_cols = ['Department', 'Gender', 'Job_Title', 'City']

# Apply one-hot encoding to the training data
X_train_processed = pd.get_dummies(X_train, columns=categorical_cols, drop_first=True)

# Apply one-hot encoding to the testing data
X_test_processed = pd.get_dummies(X_test, columns=categorical_cols, drop_first=True)

# Align columns between training and testing sets to handle cases where
# a category might be present in one set but not the other
missing_cols_train = set(X_test_processed.columns) - set(X_train_processed.columns)
for c in missing_cols_train:
    X_train_processed[c] = 0

missing_cols_test = set(X_train_processed.columns) - set(X_test_processed.columns)
for c in missing_cols_test:
    X_test_processed[c] = 0

X_test_processed = X_test_processed[X_train_processed.columns]

# Now fit the Logistic Regression model with the processed numerical data
lr.fit(X_train_processed, y_train)

lr.score(X_test_processed, y_test)

pred_test=lr.predict(X_test_processed)
pred_test

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, pred_test)
print(cm)

#import classification report from sklearn
from sklearn.metrics import classification_report
print(classification_report(y_test, pred_test)
)

"""**GridSearchCV**"""

from sklearn.model_selection import GridSearchCV
grid=GridSearchCV

param_grid = {'C': (1.0,2.0,3.0,4.0),"max_iter":(1,2,3,4)}

# Use grid search to find the optimal hyperparameters
grid = grid(lr, param_grid=param_grid)

grid.fit(X_train_processed, y_train)

grid.get_params()

# Print the optimal values for the hyperparameters
grid.best_estimator_,grid.best_params_,grid.best_score_

grid.best_params_

from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
import warnings

KF=KFold(n_splits=5) ## N split to split the testing data

from sklearn.model_selection import cross_val_predict
CVP=cross_val_predict(lr,X_train_processed,y_train,cv=5)

from sklearn.model_selection import cross_val_score
cvs=cross_val_score(lr,X_train_processed,y_train,cv=5)
cvs

cvs.max(),cvs.mean()

from sklearn.model_selection import RepeatedKFold
rp=RepeatedKFold()

from sklearn.model_selection import cross_val_predict
cvp=cross_val_predict(lr,X_train_processed,y_train,cv=5)
cvp

from sklearn.model_selection import cross_val_score
cvs1=cross_val_score(lr,X_train_processed,y_train,cv=5)
cvs1

from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import StratifiedGroupKFold

from sklearn.model_selection import cross_val_score
cvs1=cross_val_scroe(lr,X_train_processed,y_train,cv=5)
cvs1

from sklearn.model_selection import cross_val_score
cvs=cross_val_score(lr,X_train_processed,y_train,cv=5)
cvs

cvs.max(),cvs.mean()

"""**RandomizedSearchCV**"""

from sklearn.model_selection import RandomizedSearchCV
random=RandomizedSearchCV

random_grid = {'C': (1.0,2.0,3.0,4.0),"max_iter":(1,2,3,4)}

# Use grid search to find the optimal hyperparameters
random = random(lr, random_grid)

random.fit(X_train_processed,y_train)

random.score(X_test_processed,y_test)

random.get_params(),random.best_estimator_,random.best_params_,random.best_score_







"""**K FOLD**"""

from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
import warnings

KF=KFold(n_splits=5) ## N split to split the testing data

from sklearn.model_selection import cross_val_predict
CVP=cross_val_predict(lr,X_train_processed,y_train,cv=5)

from sklearn.model_selection import cross_val_score
cvs=cross_val_score(lr,X_train_processed,y_train,cv=5)
cvs

cvs.max()

cvs.mean()

"""**Repeated K-Fold Cross-Validation**"""

from sklearn.model_selection import RepeatedKFold
rp=RepeatedKFold()

from sklearn.model_selection import cross_val_predict
cvp1=cross_val_predict(lr,X_train_processed,y_train,cv=5)
cvp1

from sklearn.model_selection import cross_val_score
cvs1=cross_val_score(lr,X_train_processed,y_train,cv=5)
cvs1

cvs1.max(),cvs1.mean()

"""**Stratified K fold cross Validation**"""

from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import StratifiedGroupKFold

from sklearn.model_selection import cross_val_predict
cvp2=cross_val_predict(lr,X_train_processed,y_train,cv=5)
cvp2

from sklearn.model_selection import cross_val_score
cvs2=cross_val_score(lr,X_train_processed,y_train,cv=5)
cvs2

cvs2.max(),cvs2.mean()